#ifndef BIKE_COMMON_EVENT_H_
#define BIKE_COMMON_EVENT_H_

/* event ID */
enum EventID {
  EEVENTID_GET_MOBILE_CODE_REQ = 0x01,
  EEVENTID_GET_MOBILE_CODE_RSP = 0x02,

  EEVENTID_LOGIN_REQ = 0x03,
  EEVENTID_LOGIN_RSP = 0x04,

  EEVENTID_RECHARGE_REQ = 0x05,
  EEVENTID_RECHARGE_RSP = 0x06,

  EEVENTID_ACCOUNT_BALANCE_REQ = 0x07,
  EEVENTID_ACCOUNT_BALANCE_RSP = 0x08,

  EEVENTID_LIST_ACCOUNT_RECORDS_REQ = 0x09,
  EEVENTID_LIST_ACCOUNT_RECORDS_RSP = 0x10,

  EEVENTID_LIST_TRAVELS_REQ = 0x11,
  EEVENTID_LIST_TRAVELS_RSP = 0x12,

  EEVENTID_UNKNOWN = 0xFF
};

/* error code for event */
enum EErrorCode {
  ERRC_SUCCESS = 200,
  ERRC_INVALID_MSG = 400,
  ERRC_INVALID_DATA = 404,
  ERRC_METHOD_NOT_ALLOWED = 405,
  ERRC_PROCESS_FAILED = 406,
  ERRC_BIKE_IS_TAKEN = 407,
  ERRC_BIKE_IS_RUNNING = 408,
  ERRC_BIKE_IS_DAMAGED = 409
};

#endif  // BIKE_COMMON_EVENT_H_